### ISSUE TITLE
version for 1.20.1???

### ISSUE THREAD

**Issue by ivanlm2604** [jtorleonstudios/HUB-Better-Villages#101]

**Comment by FAKHORII** [comment]
u mean 1.21 right?

**Comment by Holmes108** [comment]
No 1.20.1. I'm also running a server with that version, and came looking for it. 

Running "Create: Perfect World" on Nitrado, and found the link for this data pack in my server log.

**Comment by jtorleonstudios** [comment]
Hi yes sooon, we'll be releasing updates to support the new versions in the next few days (from 1.20.1 to 1.21.0).

And then we will then release a version that includes the Taiga villages.

Thank you for your patience and don't forget to follow the curseforge comtpe to receive the update notification.
