### ISSUE TITLE
Server side

### ISSUE THREAD

**Issue by SteveAirCav** [jtorleonstudios/HUB-Better-Villages#102]
Hi,

Is there a server-side version for this mod?
I moved my Saved game map from single-player to a hosted server and it moaned about lots of 'unknown_structure data pack missing'.

I could use a pointer. Maybe a guide?

Thanks, Steve.

**Comment by jtorleonstudios** [comment]
Hi, There's our outdated datapack version that you can use, but currently it will remain obsolete and won't receive patches or new villages. We prefer to focus on the mod. Im sorry.
