### ISSUE TITLE
how to disable taiga villages & any updates on progress?

### ISSUE THREAD

**Issue by adamhimselfs** [jtorleonstudios/HUB-Better-Villages#108]
so i've been waiting for a taiga village update for over a year now and i dislike having them spawn around my world because of the inconsistent structure design between the vanilla village and the modded villages.

is there any way to disable taiga villages from spawning using this mod, other mods, or a datapack?
also, i'd like to know a rough estimate on when the taiga update will arrive if that's okay!

thanks in advance!

**Comment by polykatt** [comment]
you could try the [village nullifier](https://www.curseforge.com/minecraft/texture-packs/village-nullifier-datapack) datapack. just remove all the json files for the other village types and keep only the taiga village. there's also a mod version of the datapack but idk see what works i guess

hopefully the better taiga village is coming soon ^-^

**Comment by adamhimselfs** [comment]
awesome, the village nullifier datapack worked for me thanks!!

> you could try the [village nullifier](https://www.curseforge.com/minecraft/texture-packs/village-nullifier-datapack) datapack. just remove all the json files for the other village types and keep only the taiga village. there's also a mod version of the datapack but idk see what works i guess
> 
> hopefully the better taiga village is coming soon ^-^

**Comment by jtorleonstudios** [comment]
Hi  the mod is still working, we'll be releasing updates to support the new versions in the next few days.

We will then release a version that includes the Taiga villages.

Thank you for your patience and don't forget to follow the curseforge comtpe to receive the update notification.
