### ISSUE TITLE
Better taiga villages

### ISSUE THREAD

**Issue by RaptorZeraora** [jtorleonstudios/HUB-Better-Villages#109]
I just wanna ask, is better taiga villages still being worked on?  Cause the mod hasnt been updated for almost a year

**Comment by jtorleonstudios** [comment]
Hi Yes ofc, the mod is still working, we'll be releasing updates to support the new versions in the next few days.

 We will then release a version that includes the Taiga villages.
 
 Thank you for your patience and don't forget to follow the curseforge comtpe to receive the update notification.

**Comment by RaptorZeraora** [comment]
Ok, thanks for answering, I just wanted to know that

**Comment by vinnyg0621** [comment]
> Hi Yes ofc, the mod is still working, we'll be releasing updates to support the new versions in the next few days.
> 
> We will then release a version that includes the Taiga villages.
> 
> Thank you for your patience and don't forget to follow the curseforge comtpe to receive the update notification.

and what is a curseforge comt pee?

**Comment by vinnyg0621** [comment]
what is it?
