### ISSUE TITLE
armor support all around

### ISSUE THREAD

**Issue by NaixGM** [jtorleonstudios/HUB-Better-Villages#11]
I opened the world and in all the villages there is a support title for armor on each side and I don't know how to remove it. attached image.
![2022-12-14_09 57 09](https://user-images.githubusercontent.com/120580480/207629791-c90d0cde-2c26-45d0-82c0-78821b5eaf5d.png)

**Comment by jtorleonstudios** [comment]
I don't know, I don't think the mod is responsible for these armor_stands
