### ISSUE TITLE
Upload the Better Villages - Fabric mod to modrinth.com

### ISSUE THREAD

**Issue by joelarbaiza** [jtorleonstudios/HUB-Better-Villages#110]
Can you upload the Better Villages - Fabric mod to modrinth.com please?

**Comment by Amberslice** [comment]
Id love for this to happen :P

**Comment by SgtKaneki** [comment]
Totaly agree!

**Comment by jtorleonstudios** [comment]
We have other priorities right now than deploying our content on new platforms, we need to support the new forge loader. So it's not today's priority, sorry.
