### ISSUE TITLE
Armor stands within village houses multiplied by 4 on top of each other, when it should only be 1 armor stand. (1.20.1)

### ISSUE THREAD

**Issue by TheShadyyOneYT** [jtorleonstudios/HUB-Better-Villages#113]
Armor stands in each village house stacks 4 armor stands on top of each other when it should only be 1 armor stand per house. (reference image shows outside tent, but applies to all structures with armor stands) https://imgur.com/a/f8JGftN

Version: 1.20.1
Modloader: 0.5.11-0.16 
Fabric API: 0.92.2
Version of Mod: BetterVillages (1.20.1) 3.2.0

**Comment by romanfer1606** [comment]
Hello, were you able to solve this problem?

**Comment by TheShadyyOneYT** [comment]
> Hello, were you able to solve this problem? I would like to play with this mod but I don't like this happening

I’m not the mod maker. So now also I have no intentions exploring the code to fix this, feel free to look until the mod maker decides to read this issue and resolve it.

**Comment by jtorleonstudios** [comment]
#107 [https://github.com/jtorleonstudios/HUB-Better-Villages/issues/107](https://github.com/jtorleonstudios/HUB-Better-Villages/issues/107)

already discussed here, a version will arrive soon, thanks you for patience.
