### ISSUE TITLE
Permission to use the mod in a modpack. 

### ISSUE THREAD

**Issue by GreatSaltyLake** [jtorleonstudios/HUB-Better-Villages#115]
Hi, looking for permission to use Better Villages in my modpack and to be safe the library mod libraryferret as well! In the process of getting the pack uploaded to Modrinth for public use soon and ensuring I have any loose ends cleared before making it fully public. Thanks! Please reach out with any questions or concerns. Some info relating to the pack is on my github.

**Comment by jtorleonstudios** [comment]
Hi @GreatSaltyLake

Thank you for reaching out and opening an issue. 
- However, it's worth noting that similar inquiries have been addressed multiple times in previous discussions. To find a solution more quickly, please consider checking the resolved issues or searching the repository for relevant information 
- And this particular platform is intended for code-related issues and discussions. If you have any questions or concerns about the usage of the "All Rights Reserved" license,  I recommend checking the license documentation.
- For use in modpacks hosted on curseforge, please refer to the curseforge documentation.

If you have any code-related issues or questions, please don't hesitate to open a new issue, and I'll be happy to help.

Best regards,
@jtorleonstudios
