### ISSUE TITLE
Building Issue

### ISSUE THREAD

**Issue by JackRipperVoid** [jtorleonstudios/HUB-Better-Villages#117]
Encountered exception while building chunk meshes
It's saying that it can't invoke a code strig because the "sprite" is null
Code string: net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)
In turn, my entire game crashes when I find a village, and it will keep crashing until the village is no longer rendered
Incase you're wondering I'm playing on 1.20.1

**Comment by jtorleonstudios** [comment]
hey without a crash-log, we can do nothing =/

 reopen with crash log thanks
