### ISSUE TITLE
Suggestions for villages

### ISSUE THREAD

**Issue by 48004800** [jtorleonstudios/HUB-Better-Villages#12]
Large tracts of farmland under windmill buildings in plain villages lack water sources
![2022-12-25_10 48 25](https://user-images.githubusercontent.com/78255094/209455573-14bd8b91-a014-4e79-985b-9e979773937d.png)

The field water in snow village is frozen due to insufficient light source
![2022-12-25_10 46 14](https://user-images.githubusercontent.com/78255094/209455575-1cba2a79-b1f8-4220-8d2e-fa95a36d7933.png)

The compost bucket causes damage to the farmland, and farmers will trample on the farmland when standing on the compost bucket
![2022-12-25_10 48 10](https://user-images.githubusercontent.com/78255094/209455583-4c3c6e65-4adc-4273-8a7a-dc24734c92bb.png)
The phenomenon that farmers trample on the farmland due to compost barrels exists in many fields

**Comment by 48004800** [comment]
[Uploading 2.zip…]()

**Comment by 48004800** [comment]
![2022-12-25_10 51 34](https://user-images.githubusercontent.com/78255094/209455615-332c7e29-00d4-43e3-b759-4749b1d13220.png)
The fence of this kind of building is too low, so that villagers can jump onto the camp fire first and then climb over the fence.

This problem exists in all villages.

**Comment by 48004800** [comment]
![2022-12-25_10 58 00](https://user-images.githubusercontent.com/78255094/209455685-55bc9c5b-43d5-4150-91c1-edbd40b8515c.png)
I think it is better to give villagers some work blocks and set up exits than simply imprison them

**Comment by 48004800** [comment]
I clicked in a wrong place.

**Comment by 48004800** [comment]
I used a new version of mod. But I found that none of the issues were fixed.

**Comment by jtorleonstudios** [comment]
> I used a new version of mod. But I found that none of the issues were fixed.

Coming soon, thank you for your patience. (_We don't forget any issue don't worry, it will be solved soon_)

**Comment by jtorleonstudios** [comment]
fixed in the next version:
- added light source farmland snowy village
- added water source farmland plain village
- remove campfire on fence (replace leave block 1x1)
- composter moved (plain and snowy village)
