### ISSUE TITLE
fix water problems & useless glass

### ISSUE THREAD

**Issue by MemeMothership1** [jtorleonstudios/HUB-Better-Villages#13]
I downloaded this mod when I created this world, and this is the first village I have come across. The village looked normal at first, but on the opposite side of the village, there is a sudden steep incline, and the buildings began spawning on each other. Is there a way this could be fixed?

![Screenshot (794)](https://user-images.githubusercontent.com/121409746/209486655-70b2b5a7-b655-4bf2-af98-83abe047d909.png)

![Screenshot (795)](https://user-images.githubusercontent.com/121409746/209486666-260cbd3a-a76f-4c74-9a70-619ee28ede60.png)

![Screenshot (796)](https://user-images.githubusercontent.com/121409746/209486675-4fc545a3-0e7f-4af3-8c56-19484a6085ff.png)

**Comment by jtorleonstudios** [comment]
fixed in the next version
