### ISSUE TITLE
Villagers AI

### ISSUE THREAD

**Issue by chrstph3r** [jtorleonstudios/HUB-Better-Villages#16]
I don't know if it is happening to just me but because of villagers intelligence is too low Villagers keep stucked in windows because of the fence gate. It can be solved by closing the fence gate.

![2023-01-11_20 47 04](https://user-images.githubusercontent.com/119836096/211966397-02f48061-a7c5-47eb-9284-2df392f03596.png)
![2023-01-11_20 47 10](https://user-images.githubusercontent.com/119836096/211966409-2d0e80ec-26c9-4e32-8a59-d201cf6cd5f0.png)
![2023-01-11_20 47 06](https://user-images.githubusercontent.com/119836096/211966430-5a88c4a9-8305-4785-ad0b-a5006b245880.png)
![2023-01-11_20 47 15](https://user-images.githubusercontent.com/119836096/211966493-028d8912-e425-4408-9abf-78c536d9fa85.png)

Because of the AI villagers can get stucked upstairs looking at the blast furnace. I don't know if it is because of the stairs or something else.

![2023-01-11_20 57 53](https://user-images.githubusercontent.com/119836096/211966742-89c4a936-7f3b-41c9-bb1f-1190059fd336.png)

![2023-01-11_20 58 15](https://user-images.githubusercontent.com/119836096/211966754-58b15b92-01f3-4802-b502-8eeb1ffce218.png)

This corral lacks of illumination and villagers can get enclosed by jumping on the camp fire and then walk to the fences. 

![2023-01-11_20 48 46](https://user-images.githubusercontent.com/119836096/211967149-83c8f2c1-376d-45c5-ba9e-45144ddf7b68.png)

**Comment by jtorleonstudios** [comment]
Thanks you for you feedback

**Comment by jtorleonstudios** [comment]
fixed in the next version:
