### ISSUE TITLE
Houses generating inside each other

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [jtorleonstudios/HUB-Better-Villages#18]
Hello!
I am using a Better village 2.0.0 - Fabric 1.19.2.
I am facing a commonly occurring issue, where houses generate inside eachother frequently.
This hinders immersion and survival experience in a major way.

![2023-02-20_11 39 47](https://user-images.githubusercontent.com/4989469/220084890-acd92514-02a2-4681-9fdd-4a21f658caec.png)
![2023-02-20_11 40 44](https://user-images.githubusercontent.com/4989469/220084899-3225d356-2fb9-412e-962c-78ef1b0fede7.png)
![2023-02-20_11 42 20](https://user-images.githubusercontent.com/4989469/220084903-7138eaee-504c-4c32-adda-d922e93d7ee8.png)
![2023-02-20_11 44 12](https://user-images.githubusercontent.com/4989469/220084907-9593e157-ff7f-4e45-9931-988bc5a93a82.png)
![2023-02-20_11 47 19](https://user-images.githubusercontent.com/4989469/220084909-e7175cce-4b8b-48f3-ae0e-c3a58e52d88e.png)
![2023-02-20_11 50 11](https://user-images.githubusercontent.com/4989469/220084913-6fc12065-65e5-4d9a-9af2-a8dac87f1b27.png)

**Comment by jtorleonstudios** [comment]
What mod do you use with it?

**Comment by ZsoltMolnarrr** [comment]
These are screenshots from my modpack.
https://curseforge.com/minecraft/modpacks/dungeons-by-daedelus/files/4410529
However, the issue happens when no other mods are installed too.

**Comment by jtorleonstudios** [comment]
Only with the desert village ? 

Thanks you for your report/infos, we will solve the issue soon

**Comment by ZsoltMolnarrr** [comment]
Other village types have the same issue, but its much less prominent, since the clipping their is less frequent and smaller.

**Comment by jtorleonstudios** [comment]
Currently (try) applicated a solution to avoid this problem, should be corrected in the next version. reopen the problem if the problem continues
