### ISSUE TITLE
Buildings generate above each othher

### ISSUE THREAD

**Issue by chrstph3r** [jtorleonstudios/HUB-Better-Villages#19]
It has happened to me several times. With this new generation system from 1.18 - 1.19, villages are broken and with this mod, houses are spawned on top of others. Also the windmill is underground.
I'm not using any world gen mod. 
Latest Library Ferret and Better Village version.
1.19.2

![2023-02-19_13 39 02](https://user-images.githubusercontent.com/119836096/220400816-4bc01dbd-fa1b-48ea-b3de-e8e761e6f51e.png)
![2023-02-19_13 38 50](https://user-images.githubusercontent.com/119836096/220400861-841b03a6-5d90-4783-9ea0-35e64949911d.png)
![2023-02-19_13 39 18](https://user-images.githubusercontent.com/119836096/220400942-748c079b-543e-455e-8063-4a78010bc174.png)
![2023-02-19_13 40 08](https://user-images.githubusercontent.com/119836096/220401012-927fdee7-5e44-4666-baf0-7d7d09f29ef9.png)

**Comment by jtorleonstudios** [comment]
Unfortunately, it is not currently possible to fix the problem, it is a problem with the vanilla generation.

We will try to improve the situation, but it is not a priority for the moment, we have to finish all the villages before changing the generation implemented by the vanilla.
