### ISSUE TITLE
No Waystone generated on Better Villages 1.18.2

### ISSUE THREAD

**Issue by RK4L** [jtorleonstudios/HUB-Better-Villages#2]
Waystones generation works properly on the world, I even adjust range to 1 and they spawn everywere but the village waystone isn't there.

Mods Installed on Forge 40.1.60 for minecraft 1.18.2:
Jade 5.2.3
Waila (Jade) 5.2.3
Practical Tools 0.1.0
JEI 9.7.0.209
Doggy Talents 2 2.5.0
Village Spawn point 1.9
Library Ferret 2.0
Goblin traders 1.7.2
Pam's Harvestcraft Food extended 1.0
Pam's Harvestcraft Food Core 1.0.1
Toro health 1.18
Rubidium 0.5.2a
Flywheel 0.6.3.81
Curios API 5.0.7.1
Create 0.5.0
Waystones 10.1.0
Collective 4.28
Journeymap 5.8.5
Citadel 1.11.3
Alex's mobs 1.18.6
AutoReg lib 1.7-53
Simple Storage Network 1.6.2
Better Village 1
Inventory HUD+ 3.4.4
Feature NBT Deadlock Be Gone 2.0.0
Sophisticated Backpacks 3.17.9.616
MrCrayfish's Furniture mod 7.0.0 pre 29
Architectury 4.5.76
Minecraft Comes Alive 7.2.0
Balm 3.1.0+0
Quark 3.2-358
Cosmetic Armor reworked 1.18.2 V2
TwilightForest 4.1.1102
Integrated Dungeons and Structures 1.2.2
Selene 1.17.9
Supplementaries 1.4.7
Corpse 1.0.1
Minecraft Dungeons 1.11.7 (Dungeons Content on curse)
Biome o' plenty 16.0.0.134
TerraBlender 1.1.0.102

**Comment by jtorleonstudios** [comment]
![image](https://user-images.githubusercontent.com/89711083/178402851-f9be67c9-9a53-44d9-9312-08ae83966c8f.png)
![image](https://user-images.githubusercontent.com/89711083/178402876-94f01639-8563-4e69-95ea-38cf291b9381.png)
I continue the tests....

**Comment by jtorleonstudios** [comment]
Ok I tested your configuration provided on the discord, our mod seems to work normally, the only thing to note is that during our test with your configuration, the first village chosen to appear and start your solo adventure, did not contain waystone.

The other villages visited during our test have a waystone generated. 

I don't know why the first village doesn't contain a waystone, maybe you should check the mod wiki and how it works or ask the mod creator.  Unless we are mistaken, I don't think that the problem comes from the "Better Villages" mod because for the moment the mod only replaces the structure files and doesn't touch any parameter of the world generation, except the size of the structures which is bigger (20x20 - 30x30 average) 

![test 1](https://media.discordapp.net/attachments/928759749170843659/996512446531514468/unknown.png?width=886&height=498)
![test 1](https://media.discordapp.net/attachments/928759749170843659/996512447303270480/unknown.png?width=1025&height=395)


![test 2](https://media.discordapp.net/attachments/928759749170843659/996512447575887902/unknown.png?width=886&height=498)
![test 2](https://media.discordapp.net/attachments/928759749170843659/996512448356044860/unknown.png?width=1025&height=116)

manifest.json
```json
{
  "minecraft": {
    "version": "1.18.2",
    "modLoaders": [
      {
        "id": "forge-40.1.60",
        "primary": true
      }
    ]
  },
  "manifestType": "minecraftModpack",
  "manifestVersion": 1,
  "name": "Test 1",
  "author": "",
  "files": [
    {
      "projectID": 422301,
      "fileID": 3866959,
      "required": true
    },
    {
      "projectID": 560323,
      "fileID": 3669114,
      "required": true
    },
    {
      "projectID": 316582,
      "fileID": 3694258,
      "required": true
    },
    {
      "projectID": 532727,
      "fileID": 3852860,
      "required": true
    },
    {
      "projectID": 419699,
      "fileID": 3855244,
      "required": true
    },
    {
      "projectID": 342584,
      "fileID": 3822132,
      "required": true
    },
    {
      "projectID": 372534,
      "fileID": 3740562,
      "required": true
    },
    {
      "projectID": 331936,
      "fileID": 3783096,
      "required": true
    },
    {
      "projectID": 618298,
      "fileID": 3866953,
      "required": true
    },
    {
      "projectID": 220318,
      "fileID": 3759236,
      "required": true
    },
    {
      "projectID": 615352,
      "fileID": 3864305,
      "required": true
    },
    {
      "projectID": 499980,
      "fileID": 3842421,
      "required": true
    },
    {
      "projectID": 423533,
      "fileID": 3798190,
      "required": true
    },
    {
      "projectID": 268495,
      "fileID": 3868680,
      "required": true
    },
    {
      "projectID": 363703,
      "fileID": 3780535,
      "required": true
    },
    {
      "projectID": 357540,
      "fileID": 3565981,
      "required": true
    },
    {
      "projectID": 535291,
      "fileID": 3864253,
      "required": true
    },
    {
      "projectID": 55438,
      "fileID": 3683524,
      "required": true
    },
    {
      "projectID": 402231,
      "fileID": 3740472,
      "required": true
    },
    {
      "projectID": 605375,
      "fileID": 3867149,
      "required": true
    },
    {
      "projectID": 412082,
      "fileID": 3871187,
      "required": true
    },
    {
      "projectID": 271050,
      "fileID": 3705819,
      "required": true
    },
    {
      "projectID": 324717,
      "fileID": 3865918,
      "required": true
    },
    {
      "projectID": 426558,
      "fileID": 3853078,
      "required": true
    },
    {
      "projectID": 238222,
      "fileID": 3847103,
      "required": true
    },
    {
      "projectID": 486392,
      "fileID": 3871082,
      "required": true
    },
    {
      "projectID": 227639,
      "fileID": 3868236,
      "required": true
    },
    {
      "projectID": 245733,
      "fileID": 3556931,
      "required": true
    },
    {
      "projectID": 243121,
      "fileID": 3840125,
      "required": true
    },
    {
      "projectID": 32274,
      "fileID": 3820040,
      "required": true
    },
    {
      "projectID": 531761,
      "fileID": 3830790,
      "required": true
    },
    {
      "projectID": 250363,
      "fileID": 3642382,
      "required": true
    },
    {
      "projectID": 309927,
      "fileID": 3841948,
      "required": true
    },
    {
      "projectID": 328085,
      "fileID": 3871258,
      "required": true
    },
    {
      "projectID": 347381,
      "fileID": 3669142,
      "required": true
    },
    {
      "projectID": 563928,
      "fileID": 3816497,
      "required": true
    },
    {
      "projectID": 237307,
      "fileID": 3738144,
      "required": true
    },
    {
      "projectID": 574856,
      "fileID": 3749094,
      "required": true
    },
    {
      "projectID": 245755,
      "fileID": 3830849,
      "required": true
    }
  ],
  "overrides": "overrides"
}
```
