### ISSUE TITLE
You forgot a Glass Block at the spring

### ISSUE THREAD

**Issue by SpigotDE** [jtorleonstudios/HUB-Better-Villages#27]
![2023-04-17_11 46 51](https://user-images.githubusercontent.com/97298005/232449074-17d0ed80-fcfd-487c-9bea-8c70487aacb3.png)

**Comment by jtorleonstudios** [comment]
duplicate https://github.com/jtorleonstudios/HUB-Better-Villages/issues/13  

Will be fixed soon thanks you for your feedback
