### ISSUE TITLE
Cannot enabled Ice and Fire compatibility with Better Village on 1.18.2

### ISSUE THREAD

**Issue by Erxical** [jtorleonstudios/HUB-Better-Villages#29]
I got this error message when running the server.
Ice And Fire compatibility is not enabled for Better Village and Ice And Fire is present in your mod list.
     - Please install the datapack for better compatibility between Better Villages and Ice And Fire.
     - You can find the datapack URL in the `compatibility` section of the Better Villages description.
     - URL=https://www.curseforge.com/minecraft/mc-mods/better-village-forge

Although I already paste the datapack file in world/datapacks
Better Village is 3.1.0
Ice And Fire is 2.1.12

**Comment by jtorleonstudios** [comment]
Do you have the latest version of the datapack?

If yes, please provide the complete log

**Comment by Erxical** [comment]
I have the latest version (the one uploaded on Apr, 20)

I'm not sure if this is the one  you ask for but here is what I found
[latest.log](https://github.com/jtorleonstudios/HUB-Better-Villages/files/11364465/latest.log)

**Comment by jtorleonstudios** [comment]
Ok sorry (little mistake in the file path...) new versions are being downloaded/approved

![image](https://user-images.githubusercontent.com/89711083/235434975-9fcc95f6-460e-4198-8df5-c8969b7bafe3.png)

**Comment by Erxical** [comment]
Thank you so much

**Comment by DjGuetta** [comment]
How do I install it on my server? I'm playing on 1.16.5 and I get the same message
