### ISSUE TITLE
Crash with Library Ferret 2.5.0 (any mc version) [READ BEFORE OPEN ISSUE]

### ISSUE THREAD

**Issue by Alucard987** [jtorleonstudios/HUB-Better-Villages#3]
i trying to get this mod but the mod can't identify de library ferret mod. who i can solve it.

**Comment by jtorleonstudios** [comment]
don't update library ferret, this mod require library ferret 2.0.0 no 2.5.0

**Comment by jklw10** [comment]
what if another mod need 2.5.1 ? can i have both? and curseforge probably doesn't like having both.

**Comment by jtorleonstudios** [comment]
updated and fixed
