### ISSUE TITLE
Animal scattering and the glass block

### ISSUE THREAD

**Issue by BlackAures1** [jtorleonstudios/HUB-Better-Villages#33]
1. The first problem is that because of the hay and other blocks inside the pen, the animals always run away.
![image](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/43911230/37b1c0e5-3f1f-4b15-8202-35346507332f)

2. I think you already know this, but you have a glass block flying around
![image](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/43911230/4c6797dc-5a56-4653-9a94-9e948e81c258)

**Comment by jtorleonstudios** [comment]
fixed in the next version:
- glass block removed
- added space (2block) between fence and hay bale 
- campfire on fence replace by other block 1x1
