### ISSUE TITLE
[small bug]Leveling the terrain

### ISSUE THREAD

**Issue by LFMaozi** [jtorleonstudios/HUB-Better-Villages#34]
Sometimes the village is generated entirely hang in the air/halfly buried underground
Maybe the terrain leveling mekanism should be polished or just keep villages away from excess drop
(i'm using terrain datapacks [William Wythers' Overhauled Overworld] and other biome mods)
mod version: 3.1.0
game version: 1.18.2
<a href="https://ibb.co/fxQmC6k"><img src="https://i.ibb.co/vjD2Jy3/2023-06-01-03-48-45.png" alt="2023-06-01-03-48-45" border="0"></a>
<a href="https://ibb.co/nD2XVpd"><img src="https://i.ibb.co/tbf0NRj/2023-06-01-03-47-44.png" alt="2023-06-01-03-47-44" border="0"></a>

**Comment by jtorleonstudios** [comment]
The mod doesn't modify any worldgen's parameters, and this bad generation is already present with vanilla villages.

No changes world generation parameters are planned.
