### ISSUE TITLE
Verdure modded items getting in way of village generation (1.18.2)

### ISSUE THREAD

**Issue by xFirefalconx** [jtorleonstudios/HUB-Better-Villages#35]
Village buildings get generated but occasionally, there are blocks from the mod "Verdure" (https://www.curseforge.com/minecraft/mc-mods/verdure) which generate falsely. If it is an item called "verdure:rock", the floor of the building as well will be replaced by the rock. 
Flowers spawn on the floor of brick block rooms. 
I don't know if you can do anything about it, I thought you could take a look though. 

![grafik](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106652912/e55b36f4-2b78-457b-8d48-becc06c1c146)

I might make a report on their side as well. 

verdure-1.18.2-1.1.3a.jar
bettervillage-forge-1.18.2-3.1.0.jar
Forge 40.2.4
Minecraft 1.18.2

**Comment by jtorleonstudios** [comment]
will soon be corrected, the problem is with us

**Comment by jtorleonstudios** [comment]
# #32

**Comment by jtorleonstudios** [comment]
#32
