### ISSUE TITLE
PLEASE 1.20 UPDATE

### ISSUE THREAD

**Issue by FAKHORII** [jtorleonstudios/HUB-Better-Villages#39]
Im pretty sure we all would love and appreciate a cherry village! so is the 1.20 version coming any soon?, even without the cherry village!

**Comment by jtorleonstudios** [comment]
yes the update is planned, it will be released this month if not before the end of the month

I note the cherry village idea, but the taiga village is a priority, as is correcting the various problems.

**Comment by FAKHORII** [comment]
U just brought happiness to me, thank u so much I really appreciate ur work, this mod makes the whole game alive really, and I just cant wait to see how the cherry village would look like, pretty sure it would be absolutely stunning!
thank u so much <3

**Comment by jtorleonstudios** [comment]
thank you and welcome to github

**Comment by ItsMrCatGaming** [comment]
can the 1.19.4 version of the mod still be compactable for 1.20.1?

**Comment by jtorleonstudios** [comment]
> can the 1.19.4 version of the mod still be compactable for 1.20.1?

No, is for 1.19.4, wait the update thanks you

**Comment by FAKHORII** [comment]
Yoo thank u so much I already got it yesterday the moment u released it XD
I have a question tho, I trimmed my world and removed old villages chunks even around them, then added the mod but it didn't generate villages there, so does it require more space or something for a village to generate in the place of the old villages ?

**Comment by jtorleonstudios** [comment]
If the chunk has not yet been generated, then it can be generated

**Comment by FAKHORII** [comment]
I deleted the previous normal villages chunks with MCA selector (a program deletes chunks) so they can regenerate again, but no moded villages took the spot of the normal ones, except 1 out of 4 I tested, so my question is WHY so, does the moded villages need more space or something?
u don't have to answer anything its just that Im curious why it didn't work in this case that's all

**Comment by jtorleonstudios** [comment]
You can check if everything works with some command

`/tp [player] 20000 70 20000` and `/locate structures [village]`

**Comment by FAKHORII** [comment]
Im sorry to disturb u, I really dont mean to take ur time, u didn't understand my little issue I guess, 
I explored in my world and found 4 villages before u update the mod, so after u did, I want those same villages to be moded and changed to the ones in the mod, in order to do that I have to delete those entire chunks from my world so they generate again with the mod being installed, I did that but 3 from 4 villages got entirely deleted and it generated just normal terrain like there should be no village there, but there was ofcourse... I was wondering why with the mod no villages replaced the areas of the old ones!?
idk what u have there in the mod not that I know much at all so Im assuming these questions
does the mod lowers the rate of villages spawn? or does a village require bigger space than vanilla villages?.... things like that

again I'm sorry for making u read all this drama, u don't have to reply or bother, its just a chat basically, not a problem
thank u for everything.. <3

**Comment by jtorleonstudios** [comment]
I understood the problem, but I don't know the tool you use, so I couldn't answer your question. But check if the generation of new villages works as expected at a more distant distance (chunk never generated), if this is the case, then I can not help you. 

However, the mod does not modify the world generation parameters, so there is no change in the generation rate.

**Comment by FAKHORII** [comment]
thank u for taking the time, the mod works fine, I explored other villages entirely new and it works absolutely fine, apparently the tool I used is popular, I searched for such thing just for ur mod to regenerate those old villages, this MCAselector deletes chunks as they never existed and when u explore them again the generate as new, with whatever generation mod included, was surprised that better villages mod didn't generate a village in the place of the old one, I got a normal terrain instead when included ur mod but without it the old village would still generate there... anyways... ur mod is beautiful and ur work too, have a great day sir and take care of u

**Comment by jtorleonstudios** [comment]
interesting, maybe the center piece doesn't have the required conditions for generation at this location, I don't know exactly it's just a suposition, thanks for the information I'll look into it.
