### ISSUE TITLE
模组版权（Mod Copyright）

### ISSUE THREAD

**Issue by MCxiaoyi** [jtorleonstudios/HUB-Better-Villages#40]
我是一位中国人，下段话由AI翻译而成
中文：
作者可以在CurseForge网站上写明吗？
该模组可以加入自制的整合包吗？
English：
I am a Chinese, and the English is translated by AI.
Can the author specify this on the CurseForge website?
Can this mod be added to a homemade modpack?

**Comment by jtorleonstudios** [comment]
Hi

All mod JTL is **ALL RIGHT RESERVED**

So **no redistribution of the JAR is allowed,** you can create a personal modpack or a modpack on curseforge (only on curseforge), no other redistribution is allowed.

If you're creating a server, you'll need to create a modpack on curseforge to share your modlist with other players (curseforge only).
