### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by invizbleRope** [jtorleonstudios/HUB-Better-Villages#44]
It is fixed after I download the ferret lib and have it installed on both sever and client.

Thank you!

This is the last mod I added to my server.  Everything was working before.

Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bettervillage'!

[latest.log](https://github.com/jtorleonstudios/HUB-Better-Villages/files/11843958/latest.log)

**Comment by jtorleonstudios** [comment]
Yes Better Villages require the library on client and server
