### ISSUE TITLE
Camels don't spawn in desert villages

### ISSUE THREAD

**Issue by JessPlaysGames** [jtorleonstudios/HUB-Better-Villages#46]
Camels don't spawn in desert villages when this mod is used

**Comment by HuluTango** [comment]
Having the same problem. Loving the mod otherwise though.

**Comment by jtorleonstudios** [comment]
OK thanks you for the feedback

**Comment by jtorleonstudios** [comment]
fix released, now the camel spawn in desert (1.20.0/1.20.1)
