### ISSUE TITLE
[Enhancement] Update 1.20.1 for Better Villages - Bountiful Compatibility

### ISSUE THREAD

**Issue by DeshiDesu** [jtorleonstudios/HUB-Better-Villages#48]
Bountiful 1.20.1 for fabric has recently been released and so I'm wondering when will it be compatible with better villages?

https://www.curseforge.com/minecraft/mc-mods/bountiful-fabric/files/4607599

**Comment by jtorleonstudios** [comment]
Yes of course, thanks you for the information
