### ISSUE TITLE
Random blocks in villages

### ISSUE THREAD

**Issue by ual1n** [jtorleonstudios/HUB-Better-Villages#49]
Well, today I downloaded the mod to use because I liked the concept, but I found a detail that doesn't bother me, but could be corrected and it's a random glass block appearing near the fountain in the plains village, it's really not a problem, but it's something to be corrected and a point of attention to the other villages, since I haven't found them yet so I can't report things like that.

**Comment by jtorleonstudios** [comment]
Don't worry, this is the only glass block that can be found in a single village on a single type of building. This problem had already been pointed out to me, and I've already corrected it, but not yet deployed it. We'll have to wait for the next update, which will bring a lot of corrections.

Thanks you for your feedback

#13 

#27 

#33
