### ISSUE TITLE
Lag... (item_frame, banner etc...)

### ISSUE THREAD

**Issue by Aikirob** [jtorleonstudios/HUB-Better-Villages#5]
causes massive fps drops, need to find out why this happens and fix it

**Comment by jtorleonstudios** [comment]
yes it's planned thanks

**Comment by Faboslav** [comment]
Hello, is there any update for this? Villages are really nice, but the lag is making it so hard.

**Comment by Lenoxiduds** [comment]
Hi! I just discovered your mod. Is really excellent, I love it! 
I just wanted to know if the fix was in progress and if it would be released soon? :)

**Comment by jtorleonstudios** [comment]
update will be available in the next few hours. (**category village savanna added**)
