### ISSUE TITLE
Glass block left in plains_meeting_point_1.nbt

### ISSUE THREAD

**Issue by liopyu** [jtorleonstudios/HUB-Better-Villages#51]
I'm assuming you were using world edit to fill with structure void and/or just placing a corner structure block and forgot to break the glass block. I do this too sometimes lol 

file path is data\minecraft\structures\village\plains\town_centers\plains_meeting_point_1.nbt

**Comment by jtorleonstudios** [comment]
Yes thanks you, is already fixed in local, coming soon with the big bugfix update

> https://github.com/jtorleonstudios/HUB-Better-Villages/issues?q=is%3Aissue+glass
