### ISSUE TITLE
Villages generate in multiple layers intersecting with the terrain

### ISSUE THREAD

**Issue by Doktor42** [jtorleonstudios/HUB-Better-Villages#52]
While vanilla village only generates structures on top of the terrain without intersecting the terrain, the better village is generated on all layers and the buildings on the lower layers are grossly intersected by the terrain.

Version: bettervillage-forge-1.20.1-3.1.0.jar
Forge - 47.1.10
Seed used for pictures: -5775836182227283359 - village next to spawn
Example for one of the many intersections:
![intersection of house](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/58052837/585c09ed-4a55-45eb-9845-e30abb641758)

NNE-View:
![better_village_NNE](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/58052837/e32f1ef6-5881-4607-8c5f-d656385e54c1)
![vanilla_NNE](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/58052837/ac18818a-d5d8-4874-b606-1fcc9d04ae55)

SSW-View:
![better_village_SSW](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/58052837/487459d7-9569-4204-971b-0a0efc4692bc)
![vanilla_SSW](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/58052837/28d24843-7148-49f5-b1e7-d9ef3925b468)

**Comment by jtorleonstudios** [comment]
Will be corrected in the next version.But it will continue to generate on the different layers, perhaps we will improve this point in the near future, as it requires a modification of the generation conditions to meet the requirements. 

Thanks for the feedback
