### ISSUE TITLE
Villages not replacing vanilla

### ISSUE THREAD

**Issue by Bryteside** [jtorleonstudios/HUB-Better-Villages#57]
Playing Java 1.19.2 Forge

I've had no luck getting Better Villages to actually spawn. I've uninstalled/reinstalled, checked versions are correct, have ferretlib, game launches totally fine. Just no modded villages.

Is there a world gen setting or mod config option I'm supposed to change maybe?

Any help is very much appreciated, thanks!

**Comment by jtorleonstudios** [comment]
Hi, please paste your log or host on pastebin and give me the link

**Comment by jtorleonstudios** [comment]
I've run a few tests and everything seems to be working as expected. Without more information, I'm afraid I can't help you.

![image](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/89711083/1d5e8ace-cef8-4aad-acff-e138cd32276f)

**Comment by jtorleonstudios** [comment]
need more information
