### ISSUE TITLE
Crash when using quilt 0.20.0-Beta 5 

### ISSUE THREAD

**Issue by RWRmrfrog** [jtorleonstudios/HUB-Better-Villages#59]
I've used this mod with quilt in the past, and everything worked fine. The newest version seems to no longer work with quilt. 
[crash-2023-08-04_21.18.23-client.txt](https://github.com/jtorleonstudios/HUB-Better-Villages/files/12265406/crash-2023-08-04_21.18.23-client.txt)
![image](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/117955221/9e1bdb1a-c8ce-4931-8eee-a5893fff952d)

**Comment by jtorleonstudios** [comment]
This mod is for fabirc or forge

**Comment by AlexIIL** [comment]
I've had a quick look and it looks like `bettervillage-fabric-1.20.0-3.1.0.jar` declares a dependency on `"libraryferret":"4.0.0"`, but `bettervillage-fabric-1.20.1-3.1.0.jar` doesn't - is that intentional? Either way that causes the same crash on fabric if `Library Ferret` isn't included.

**Comment by jtorleonstudios** [comment]
Yo yes is a erreur ! Library ferret is required...

Please try with the lib  and keep  my informed  thanks you

**Comment by jtorleonstudios** [comment]
version with the fix released, thanks you.

Keep my informed if the problem continue
