### ISSUE TITLE
[Suggestion] [1.16.5] Option to change spawn rates

### ISSUE THREAD

**Issue by BigBoiSub** [jtorleonstudios/HUB-Better-Villages#6]
Hello,
It would be cool, if we got an option in config file, where we can change village spawn rates, as they are spawning quite a lot in my modpack and is causing TPS dips.

**Comment by jtorleonstudios** [comment]
Hi,

The **mod does not change the spawn** rate of villages, maybe there are other things that affect the spawn rate?

For the lag, it could be created by the number of entity in the village, because there is a lot of banner, and item_frame, **we plan to reduce the number of entities**

**Comment by BigBoiSub** [comment]
I see. Would your mod perhaps replaced villages from Repurposed structures mod, as  they add villages?

**Comment by jtorleonstudios** [comment]
The mod for the moment only replaces the villages vanilla plains, snowy, desert.
