### ISSUE TITLE
Decorative Barrels turn all villagers into Fishermen

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [jtorleonstudios/HUB-Better-Villages#60]
Hello!

This mod makes it difficult to play survival immersively, because there villages are full of Fishermen. About every second villager is a fisherman. This is because the new village structures are full of decorative Barrel blocks, those turn nearby villagers into Fishermen.

Please remove decorative barrels and keep barrels only inside fishermen specific houses.}

(Reference: https://minecraft.fandom.com/wiki/Trading#Fisherman )

**Comment by jtorleonstudios** [comment]
Yes is already fixed in local.. wait the next update
