### ISSUE TITLE
villages collide with choice therom better villages

### ISSUE THREAD

**Issue by AlphaRedknox** [jtorleonstudios/HUB-Better-Villages#61]
![2023-08-13_10 57 51](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/142169378/c69dc6bb-6480-438e-870f-174fb6885f00)

The plains village collides with the medieval village from choice theorem overhauled villages. I'm assuming this could also happen with other variants of villages in different biomes. I'm aware having two mods that do similar things could overpopulate the world, but it's not compatible as stated on the page. Maybe a compatibility data pack is needed. This is 1.19.2 btw. Not sure if this issue was addressed in 1.20+

**Comment by jtorleonstudios** [comment]
Unfortunately this isn't a problem with our mod because without our mod you would have the same problem but it would have been a vanilla village. , our mod only modifies the vanilla villages, so you'll have to see with the Choice Theoreme mod.
