### ISSUE TITLE
Modrinth Modpack Usage request

### ISSUE THREAD

**Issue by M0nkeyPr0grammer** [jtorleonstudios/HUB-Better-Villages#63]
Dear JTorlen,

I have long admired your mod, "Better Villages." I am reaching out to request permission to include it in my modpack, [Landscapes Reimagined](https://modrinth.com/modpack/landscapes-reimagined). Given that both "Better Villages (Fabric)" and "Library Ferret (Fabric)" are licensed under **All Rights Reserved**, Modrinth mandates that I obtain explicit authorization to incorporate them into my modpack. 

May I kindly request your permission to use both "Better Villages (Fabric)" and "Library Ferret (Fabric)" in my modpack? Rest assured, I will ensure proper attribution to recognize your commendable efforts and contributions.

Thank you for considering my request.

Warm regards,

M0nkeyPr0grammer

**Comment by jtorleonstudios** [comment]
please do not redistribute our content on other plateform. if you want to support us, use our content as intended, otherwise don't use/distribute it. 

This image comes from your modpack on modrinth, which I've downloaded. You've already uploaded the datapack version of the village.
![image](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/89711083/553bc754-e61b-433b-b0bf-f59a77d927b2)

**Comment by M0nkeyPr0grammer** [comment]
I will certainly refrain from doing this, also I don't know if you noticed but I did link your datapack on the main page of my modpack as I make sure to always reference anything that is implemented in my modpack.

**Comment by jtorleonstudios** [comment]
yes, I saw the mention, that's cool ! But our content is currently distributed on Curseforge, so you can always include it in your curseforge modlist.html, but redistribution of our assets is not allowed, on any platform.

**Comment by M0nkeyPr0grammer** [comment]
Alright, I will make sure to remove the datapack version of Better Villages from my pack in the next release. Is there any plans on also adding your projects to Modrinth?

**Comment by jtorleonstudios** [comment]
Maybe yes, in the future.

We already published on modrinth a few months ago, then backed off, but we're now waiting for the platform to mature and see the result.

**Comment by M0nkeyPr0grammer** [comment]
Alright, and totally understandable.  I will certainly keep on eye on when that happens as I love your builds and would love to have it to my pack. Keep up the great work!
