### ISSUE TITLE
Duplicate Armor Stands

### ISSUE THREAD

**Issue by CrimsonCrips** [jtorleonstudios/HUB-Better-Villages#78]
Issue where there are multiple armor stands inside the structures 
1.19.2
Only The Mod and Library Ferret are present
It is present in both the Forge and Fabric Versions.

**Comment by V972** [comment]
I have same issue on 1.18 Forge as well

**Comment by Jeronton** [comment]
I have the same in 1.20 on fabric

**Comment by Aceplante2** [comment]
1.18.2 forge

**Comment by jtorleonstudios** [comment]
#87
