### ISSUE TITLE
add compatibility with Ice and Fire

### ISSUE THREAD

**Issue by giova-01** [jtorleonstudios/HUB-Better-Villages#8]
All the generated villages have this ice and fire structure repeated a lot of times:
![2022-10-25_23 52 42](https://user-images.githubusercontent.com/80795034/197924896-19af43bf-63b8-4893-b60f-e777a26e72d4.png)

In this village the structure is repeated 11 times:
![2022-10-25_23 50 23](https://user-images.githubusercontent.com/80795034/197925168-a46c0a3d-c4a0-42cc-a7c8-4d1eefe07c29.png)

Another village with at least 8 of them:
![2022-10-25_23 52 23](https://user-images.githubusercontent.com/80795034/197925367-345418c6-23d8-4634-8e2f-a938d224faee.png)

let me know if you need more information. I have a lot of mods installed, but none that modify villages (Exept Better Villages of course).

**Comment by jtorleonstudios** [comment]
Alright

**Comment by jtorleonstudios** [comment]
project created, until approved by a moderator on curseforge
https://www.curseforge.com/minecraft/texture-packs/better-villages-ice-and-fire-compat-datapack

**Comment by jtorleonstudios** [comment]
Note: For a perfect compatibility, don't forget to modify the weight for the houses (if necessary) in the Ice and Fire config (instance/config/iceandfire-common.toml). 

![image](https://user-images.githubusercontent.com/89711083/229370360-fb11e9a9-c914-470f-9b39-2e292fc54362.png)
