### ISSUE TITLE
Server crashing during exploration (Unknown block type 'create:andesite_bricks')

### ISSUE THREAD

**Issue by LeaderbotX400** [jtorleonstudios/HUB-Better-Villages#80]
[Reference](https://github.com/Creators-of-Create/Create/issues/5787)

**Comment by jtorleonstudios** [comment]
https://github.com/Creators-of-Create/Create/issues/5787#issuecomment-1871378225

The problem doesn't come from better villages unless we're mistaken, better villages doesn't currently interact with Create, doesn't create any blocks, and doesn't currently add any non-vanilla blocks to the house. Unless you add a data pack that does.
