### ISSUE TITLE
Modpack usage request

### ISSUE THREAD

**Issue by WorldOfTonys** [jtorleonstudios/HUB-Better-Villages#84]
Hello, I have a question.

Could I use the Better Villages (fabric) mod for my own modpack on Modrinth? Of course I will make sure to link back to your mod page.

**Comment by jtorleonstudios** [comment]
Hi @WorldOfTonys

Thank you for reaching out and opening an issue. However, this particular platform is intended for code-related issues and discussions. If you have any questions or concerns about the usage of the "All Rights Reserved" license, I recommend checking the license documentation.

If you have any code-related issues or questions, please don't hesitate to open a new issue, and I'll be happy to help.

Best regards,
@jtorleonstudios
