### ISSUE TITLE
Better Villages and Immersive Engineering Resourcepacks

### ISSUE THREAD

**Issue by Krimatoria** [jtorleonstudios/HUB-Better-Villages#86]
Forge 43.3.5, Minecraft 1.19.2

I have installed a resource pack for the interaction of 2 mods. But the spam in the error log continues. But anyway, it seems that the resource package is not working correctly.

HUB-Better-Villages - datapack requires the installation of this mod global_packs-forge-1.19.2-1.14.5_forge.jar, I also installed it, created a new world. Nothing changes with the error anyway.

[12Feb2024 18:53:26.409] [Render thread/ERROR] [bettervillage/]: Immersive Engineering compatibility is not enabled for Better Village and Immersive Engineering is present in your mod list.
     - Please install the datapack for better compatibility between Better Villages and Immersive Engineering.
     - You can find the datapack URL in the `compatibility` section of the Better Villages description.
     - URL=https://www.curseforge.com/minecraft/mc-mods/better-village-forge

**Comment by jtorleonstudios** [comment]
hum interesting, don't worry it's not a real error that's causing problems, but indeed it's not normal that the message is still displayed even after installing the datapack, we'll check the code, we must have made a logical error at the level of checking the datapacks installed. thank you for your feedback
