### ISSUE TITLE
FPS Down Village 1.19.2 Forge (Multiple duplication of armor racks. Locked residents in blocks. Violation of the logic of the villagers..)

### ISSUE THREAD

**Issue by Krimatoria** [jtorleonstudios/HUB-Better-Villages#87]
Minecraft 1.19.2, Forge 43.3.5
Bettervillage-forge-1.19.2-3.2.0.jar
libraryferret-forge-1.19.2-4.0.0.jar
Insanity-Shader-Universal-v1.500

You can use the command to teleport to the nearest rack.
/tp @ e[type=armor_stand, sort=nearest, limit=1] (just remove the space before the letter "e")
You need a village that has such buildings in the center.
![2024-02-15_00 29 02](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/c82d94b7-5861-49e6-9000-651a1c50473a)

### > UDP: It turns out that when I examined the houses, I noticed how the armor racks were spinning very quickly, they were duplicated several times in the same place. Some residents fell into the trap with the help of a block of steps in front of the stairs, or a pile of objects blocked their way to the exit. Finding a way for a resident always seemed to put a lot of strain on TPS. I do not know what exactly loads FPS so much here, I kind of removed all the armor racks. But he's still unstable.

**Destroyed duplicates**
There are 4 armor racks in one place.
That's how much abuse I got from 4 armor racks that stood in each other
![2024-02-14_02 28 37](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/b250e7b0-5e5f-4e78-86ae-ed1d1040cb4d)
That's how many duplicate racks the iron armor had. I got as many as 4 sets))))
![2024-02-15_00 25 24](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/a9f224e6-9516-4241-9b12-b9165000bf05)
![2024-02-14_02 25 15](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/47226fc9-e61d-4929-825a-11a4d9499e5f)
![2024-02-09_11 39 48](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/68873070-c758-4337-98ba-696eba97779f)
![2024-02-09_11 40 08](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/efb41c21-5f06-46d0-b14f-d457e48bae40)
**Again, in another house, armor racks cloned in one place cause lag.**
![2024-02-09_11 39 50](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/c993457e-aa93-4376-be05-eb5fd1d4cd9c)
![2024-02-09_11 39 48](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/275472c0-d0a9-44ea-9f26-dcd7324a4d78)
![2024-02-09_11 44 40](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/999e02da-714e-4f4a-91a0-1a92656956f5)

### Two locals are trapped in a stairwell somehow
![2024-02-09_11 43 59](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/554ee73e-2b08-41d5-8e87-c904efa3e0bb)
![2024-02-09_11 44 13](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/59909469-a5df-4cac-9140-416952240a71)
The same thing on the other side.
![2024-02-09_12 00 52](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/3b54d2bb-77c1-4e0c-90f5-9f0ceb38235e)
### The resident cannot leave the house, as he first opens the door where the food is and stops. I removed the doors and he quietly left.
![2024-02-09_12 03 50](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/b445c3cc-02ca-459d-aade-a9e14c4dd9ab)
![2024-02-09_12 03 24](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/8d2d7b89-1fae-4b6d-93ed-ed3fa1377e05)
![2024-02-09_12 03 27](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/c2ce721d-00cd-4b00-b7d8-95b01014fef3)
![2024-02-09_12 03 45](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/385c1743-d982-4cba-a00a-9bdd351bbe25)

> **Updated.Updated. This text below and screenshots were before the problems with the armor racks were discovered and locked by residents..**

Mmm, it has something to do with Shaders. Since when they are disabled, FPS does not drop so much. But at the same time it concerns the village.
![2024-02-09_10 34 44](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/6fb241bc-ae23-4019-b4bd-356301054463)

I do not know what the problem is with this place, but it is fixed when I look the other way. At the same time, there are also local villagers there. Perhaps some object is causing the problem. As soon as I turn away from the center, everything stabilizes.

![2024-02-09_11 33 07](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/440326e8-725a-410a-aede-c1fb2f448aeb)
![2024-02-09_11 32 53](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/8f3ba592-fb5f-4baa-ba34-0687939be4a0)
![2024-02-09_11 33 03](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/106809386/94ea7e63-3019-4025-bc12-e37b83231a67)

**Comment by jtorleonstudios** [comment]
hi. thanks you for your report ! we will correct this error in the next version

**Comment by Krimatoria** [comment]
> привет. спасибо за ваш отчет! мы исправим эту ошибку в следующей версии

Nice)

**Comment by jtorleonstudios** [comment]
Hi. Ok just to keep you up to date: we've temporarily removed all armor stand type entities, we'll replace them later with custom blocks without entities to avoid having an entity for each block.
 
I've just reread your message completely, I think we haven't forgotten anything, but we'll check one last time before releasing the update. Thank you very much for your feedback.

 The update should released in the next few days. Feel free to continue the discussion here if you find other things that should be fixed.

**Comment by Krimatoria** [comment]
> Hi. Ok just to keep you up to date: we've temporarily removed all armor stand type entities, we'll replace them later with custom blocks without entities to avoid having an entity for each block.
> 
> I've just reread your message completely, I think we haven't forgotten anything, but we'll check one last time before releasing the update. Thank you very much for your feedback.
> 
> The update should released in the next few days. Feel free to continue the discussion here if you find other things that should be fixed.

By the way, I can check for 1.20.1 since it's on it right now. Is there such a problem there)

**Comment by jtorleonstudios** [comment]
no it's not necessary, I've fixed the problem, and yes is present on all versions. Because our structures are built on version 1.16 and then we manually update to the other versions. So we've fixed the problem on version 1.16, which will automatically be reflected on all other versions.

**Comment by Krimatoria** [comment]
> no thanks you, it's not necessary, I've fixed the problem, and yes is present on all versions. Because our structures are built on version 1.16 and then we manually update to the other versions. So we've fixed the problem on version 1.16, which will automatically be reflected on all other versions.

Then I'll add them to my build) Thanks for the fix)
