### ISSUE TITLE
Modpack permission (Modrinth)

### ISSUE THREAD

**Issue by fl0wynx** [jtorleonstudios/HUB-Better-Villages#88]
Hi, I'm making a big modpack with quests that I'm uploading on Modrinth.

Can I include your 'Better Villages - Forge' and 'Library Ferret - Forge'? I'll link them back in the modpack's description.

fl0wy.nx

**Comment by fl0wynx** [comment]
Why did you close it? Could you answer me please?

**Comment by jtorleonstudios** [comment]
Hi @fl0wynx

Thank you for reaching out and opening an issue. However, this particular platform is intended for code-related issues and discussions. If you have any questions or concerns about the usage of the "All Rights Reserved" license,  I recommend checking the license documentation.

If you have any code-related issues or questions, please don't hesitate to open a new issue, and I'll be happy to help.

Best regards,
@jtorleonstudios

**Comment by fl0wynx** [comment]
"As a copyright owner, you might use the “All rights reserved” notice to indicate that you retain all rights provided by copyright law. As such, another person cannot reproduce, distribute and/or adapt any part of the work without your permission."

Tht's why I've asked permission to you :smile:
