### ISSUE TITLE
Create compatibility?

### ISSUE THREAD

**Issue by BubbyCraft** [jtorleonstudios/HUB-Better-Villages#95]
Hello, I have seen this mod showcased on a lot of YouTube playthroughs with the Create mod and they all have windmills that are powered by the create mod to make them actually work in the world as what I can only determine is a pre generated structure. Whenever I use this mod and load up any new world, even using it by itself or in the exact same mod pack as a video that had the working windmills, they are not functioning. The sails are always just blocks of wool instead of create sails, and there is no windmill bearing. Am I doing something wrong?

**Comment by jtorleonstudios** [comment]
Do you have a video example for me? Thanks you

**Comment by BubbyCraft** [comment]
https://www.twitch.tv/videos/2146736350?t=00h32m18s
It should be set to start playing at roughly 32minutes in, but that was last night in a brand new world.

**Comment by BubbyCraft** [comment]
![image](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/152036879/b72533c2-79ed-479b-9f93-e76a191f0477)
![image](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/152036879/8d893068-f588-4855-8e59-c72141e8b9d2)
![image](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/152036879/2fec60ca-f16b-422c-b281-af5ac18dfbe4)
![image](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/152036879/d0038792-b758-458d-9081-9f766ea7539a)
![image](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/152036879/fc428874-f5de-4d5b-bf05-763708fd8674)
![image](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/152036879/aefb0d59-21e5-4a6f-a2d8-a42be8254c10)

**Comment by BubbyCraft** [comment]
I made sure to include the coordinates too so that it shows me moving around. I have flown all over so many new worlds thinking that I would eventually find one with a "working" windmill, but I never have. I would be happy to do a screen share as well.

**Comment by jtorleonstudios** [comment]
It's normal, the better villages not default mod doesn't include the create data pack. And our data pack for Create is not yet published on curseforge ahah So I'm curious to know who makes the windmill go working.

So here's what I think of the situation:
- you're missing a datapack or mod on your modpack.
- you've watched a video that uses the modpack/datapack or mod you're missing to animate the windmill.

Unfortunately I don't know what datapack or mod, modifies our content and our datapack is not yet published on curseforge so unfortunately I couldn't help you, the only thing I could say is to be patient and wait for our publication or look for the mod or datapack that modifies/animates/replaces the windmill.

**Comment by BubbyCraft** [comment]
I have asked so many youtubers about this though and they all say the same thing that they just installed Mr. Beardstone's modpack and it had working windmills automatically. 

https://www.youtube.com/watch?v=bfdgHv8iy3Y
Skip to 3:02 for the windmill working. This youtuber installed the same modpack I have as well and his windmills work. There are no mods in the pack that make the windmills work (that I know of) as well

**Comment by BubbyCraft** [comment]
I posted my reply before I saw yours. Thank you. I would much rather wait for your update instead of looking into the shady data packs out there for this sort of thing. Thank you so much for your help.
