### ISSUE TITLE
Hows the taiga update going? if you don't mind me asking

### ISSUE THREAD

**Issue by Dooisco394** [jtorleonstudios/HUB-Better-Villages#97]

**Comment by vinnyg0621** [comment]
I have the same question. I'm waiting for the coniferous forest village update too. I want to play on my survival map with it. but I don't see any answers here yet...

...if you don't mind me asking too

**Comment by jtorleonstudios** [comment]
Hi, it will be released in the next few days
Thanks you for your patience.

**Comment by vinnyg0621** [comment]
hey, i had a dream last night that the coniferous forest villages were updated! :D

**Comment by vinnyg0621** [comment]
i'm hyped for the village update of the final, and best biome! :D
